package hu.norbisquest.nq1.client.game.actors;

import java.util.HashMap;
import java.util.Map;

public class NorbiText {
    public static Map<Integer, String> lines;
	static {
		lines = new HashMap<>();
		lines.put(0, "");
		lines.put(1, "Kérek egy bérletet.");
		lines.put(2, "Kérek egy jegyet.");
		lines.put(3, "Milyen újságokat tetszik árulni?");
		lines.put(4, "Tetszik tudni, hogy egy csöves tanyázik a bódé oldalában?");
		lines.put(5, "Melyik a legolcsóbb újság?");
		lines.put(6, "Kérek egy újságot!");
		lines.put(7, "Kérek egy Délmagyar különkiadást.");
		lines.put(8, "Viszlát!");
		lines.put(9, "Csókolom!");
		lines.put(10, "Uhh, így felment az ára?");
		lines.put(11, "Ja tényleg, most látom. Köszönöm.");
		lines.put(12, "Elzavarjam?");
		lines.put(13, "Na jó.");
		lines.put(14, "Értem");
		lines.put(15, "Egy olyat, ami ott van felül.");
		lines.put(16, "Ja, az elég olcsónak néz ki");
		lines.put(17, "Igen, még egyet. Nem lehet többet is venni?");
		lines.put(18, "Upsz, most nézem, annyi nincs nálam.");
		lines.put(19, "Ok");
		lines.put(20, "Sajnos nincs egyikse.");
		lines.put(21, "Jegyem az van.");
		lines.put(22, "Csak vicceltem, van jegyem!");
		lines.put(23, "Ok, ok, nem kell aggódni.");
		lines.put(24, "Ok, ok, nem kell felkapni a vizet.");
		lines.put(25, "Hello! Mi a pörgés?");
		lines.put(26, "Húzz a klub elől koszos punk!");
		lines.put(448, "Tudnál segíteni?");
		lines.put(27, "Nincs egy kis pénzed?");
		lines.put(449, "Van egy kés hátul az asztalba szorulva...");
		lines.put(28, "Szurdi keresi a láncát. Nem tudsz róla valamit?");
		lines.put(29, "Na csáó, megyek.");
		lines.put(30, "Norbi vagyok.");
		lines.put(31, "Nem az a Norbi!");
		lines.put(32, "Semmi érdekeset, csak beköszöntem.");
		lines.put(33, "Bunyót akarsz? Állok elébe.");
		lines.put(34, "Na majd meglátjuk, most nincs idõm ilyenkre.");
		lines.put(35, "Nem, csak sürgõs dolgom van.");
		lines.put(36, "Kár, be kéne fizetnem a tagságit Szurdinak.");
		lines.put(37, "Akkor nincs hol próbálni a zenekarral.");
		lines.put(38, "A hátsó próbateremben van egy kés az asztalba szorulva, segítenél kihúzni?");
		lines.put(39, "Legenda?");
		lines.put(40, "Hát ilyen formában még nem.");
		lines.put(41, "Na de mindegy, majd valahogy megoldom.");
		lines.put(42, "Szereli a wc-t és eltűnt a lehúzó.");
		lines.put(43, "Ja, én is arra gondoltam.");
		lines.put(44, "Csak most nem fog segíteni, amíg nem találom meg.");
		lines.put(45, "Tiszteletem, Uram!");
		lines.put(46, "Kotródj az utcánkból, mocskos csöves!");
		lines.put(47, "Mit tetszik árulni?");
		lines.put(48, "Vehetek a pénzbõl?");
		lines.put(49, "És mit kapok cserébe?");	
		lines.put(50, "Minek magának pénz? Tele a kalapja");
		lines.put(51, "Visszakérhetném az újságot?");		
		lines.put(52, "Tudja, hogy egy banánhéj van a hajában?");
		lines.put(53, "Na mentem.");
		lines.put(54, "Hívom a haverokat és ellátjuk a baját!");
		lines.put(55, "Nem vicceltem, már hívom is őket..");
	    lines.put(56, "Akkor minek ült ki ide? ");
	    lines.put(57, "Legalább énekelne, vagy valami.");
	    lines.put(58, "Vááá! Hagyja abba! Inkább maradjon csöndben.");
	    lines.put(59, "Persze, nehéz munka. Egész nap itt ül gondolom.");
	    lines.put(60, "Nem kell, elhiszem.");
	    lines.put(61, "Hát pedig a gazdaság nem így működik.");
	    lines.put(62, "Ha fizetek valamiért, akkor cserébe el is várok valamit.");
	    lines.put(63, "De a pénzem azért kéne, mi?");
	    lines.put(64, "És mire fogja költeni?");
	    lines.put(65, "Gondoltam. Arra nem adok.");
	    lines.put(66, "De nekem kéne.");
	    lines.put(68, "Ebben a szekrényben vannak a cuccaim.");
	    lines.put(69, "Lássuk mi van itt.");  
	    lines.put(70, "Nincs itt semmi, ami most kellene.");  
	    lines.put(71, "Itt a perselyem az összes spórolt pénzemmel.");  
	    lines.put(72, "Azt hiszem erre most szükségem lesz.");  
	    lines.put(73, "Az íróasztalom és egyben számítógépasztalom.");
	    lines.put(74, "Nem kell innen semmi most.");  
	    lines.put(75, "Szurdi már valószínűleg lenn van a klubban.");
	    lines.put(76, "Össze kéne kaparnom kétezret a tagságira.");
	    lines.put(77, "Nézzük mit rejt a fiók.");
	    lines.put(78, "Né, itt a perselyem kulcsa!");
	    lines.put(79, "Akkor ezt elteszem.");
	    lines.put(80, "Tele van mindenféle kacattal, de egyikre sincs most szükségem.");
	    lines.put(81, "Prizönbrék, a kedvenc sorozatom.");  
	    lines.put(82, "Ha egyszer majd börtönbe kerülök, akkor tudni fogom, hogy kell kiszabadulni.");  
	    lines.put(83, "Nekem ott tetszik ahol van, nem szedem le.");  
	    lines.put(84, "Innen belátható fél Szeged.");  
	    lines.put(85, "Nem látok most semmi érdekeset.");  
	    lines.put(86, "Nem kell kinyitni, pont jó a hõmérséklet itt benn.");  
		lines.put(87, "Ezen szoktam nézni a filmeket.");  
	    lines.put(88, "Most nincs idõ filmezni.");  
	    lines.put(89, "A tévém.");
	    lines.put(90, "Most nem nézek tévét.");
	    lines.put(91, "Lássuk van e valami értelmes műsor.");
	    lines.put(92, "Semmi érdekes.");
	    lines.put(93, "Mindenféle fajta és típusú könyv.");  
	    lines.put(94, "Felét nem olvastam még.");  
	    lines.put(95, "Nem most fogok elkezdeni olvasni.");  
	    lines.put(96, "Nincs itt titkos átjáró, amit egy könyv elmozdításával nyitok ki.");  
	    lines.put(97, "A pihe-puha ágyikóm.");  
	    lines.put(98, "Most nincs idő pihenni.");  
	    lines.put(99, "Mindenféle dolgot tartok bennük.");  
	    lines.put(100, "Most nincs idő erre.");  
	    lines.put(101, "Mókás figurák vannak rajta.");  
	    lines.put(102, "Jó ez ahol van.");  
	    lines.put(103, "Elosztó.");  
	    lines.put(104, "Nem nyúlok bele, mert megráz az áram.");  
	    lines.put(105, "Nem poros. De amúgy se ezzel kéne leporolni.");  
	    lines.put(106, "Nincs bezárva. És egyébként se ennek a kulcsa.");  
	    lines.put(107, "A szobám ajtaja.");  
	    lines.put(108, "Minek csukjam be?");  
	    lines.put(109, "Megpróbálom kihúzni.");  
	    lines.put(110, "Nem megy. Nagyon be van szorulva. "
	    		+ "Talán be kéne olajozni, vagy valami.");
	    lines.put(111, "Undorító.");
	    lines.put(112, "Egy millióért se nyúlnék bele.");
	    lines.put(113, "Nem látok benne már semmi érdekeset.");
	    lines.put(114, "Annyira tele van, hogy már nem fér bele a szemét.");  
	    lines.put(115, "Látok benne valamit. Valami hosszabb tárggyal ki kéne piszkálni.");
	    lines.put(116, "Dehogy nyúlok bele.");
	    lines.put(117, "Már egyszer feltúrtam.");
	    lines.put(118, "Ezzel megnézhetem van-e benne valami hasznos.");
	    lines.put(119, "Egy félig elfogyassztott sör. Lehet, hogy még jó lesz valamire.");
	    lines.put(120, "Nem hiszem, hogy van benne még más használható dolog.");
	    lines.put(121, "Beletúrok egy kicsit, hátha akad valami érdekes.");
	    lines.put(122, "Nicsak, egy teljesen ép szendvics.");
	    lines.put(123, "Leporolom egy kicsit.");

	    lines.put(124, "Valaki lehajította ide a kabátját.");
	    lines.put(125, "Már átkutattam egyszer.");
	    lines.put(126, "Nézzük mit rejtenek a zsebek.");
	    lines.put(127, "Egy doboz cigi van csak benne.");
	    lines.put(128, "Villanykapcsoló.");
	    lines.put(129, "Nem oltom le, mert akkor szart se látnék.");
	    lines.put(130, "Konnektor");
	    lines.put(131, "Nem kockáztatom meg az áramütést.");
	    lines.put(132, "Egy kés az asztalba szorulva.");
	    lines.put(133, "Nem egészen olajos állagú ez a sör."); 
	    lines.put(134, "Csak széttörne.");
	    lines.put(135, "Nem dobom ki.");
	    lines.put(136, "Az én kedves Marsal erősítőm.");
	    lines.put(137, "Sajnos nem működik.");
	    lines.put(138, "Szia Marsal!");
	    lines.put(139, "Nem automata, hogy pénzt kelljen dobálni bele.");
	    lines.put(140, "Ez nem portörlő, hanem egy szaros wc-kefe!");
	    lines.put(141, "Nem öntöm rá, még tönkremegy.");
        lines.put(142, "Nem akarom tönkretenni!");
	    lines.put(143, "Végre, ki tudom cserélni");
	    lines.put(144, "Lássuk, hova is kell bedugni.");
	    lines.put(145, "Ez az, sikerült.");
	    lines.put(146, "Ki is próbálom, hozom a gitárom.");
	    lines.put(147, "A szupermárkás Adios cipőm. Eredeti kínai.");
	    lines.put(148, "Jó az ami rajtam van.");
	    lines.put(149, "Az a wc.");
	    lines.put(150, "Ha jól látom, most éppen senki sincs bent.");
	    lines.put(151, "Ez csörög, ha valaki fel akar jönni.");
	    lines.put(152, "Ez csak arra jó, ha valaki fel akar jönni. Most nem csörög.");
	    lines.put(153, "Azon vannak a kulcsaink. Most épp nincs rajta egy se.");
	    lines.put(154, "Nincs rajta kulcs.");
	    lines.put(155, "A fürdõszoba villanykapcsolója.");
	    lines.put(156, "Nincs okom kapcsolgatni.");
	    lines.put(157, "A fürdőszoba ajtaja.");
	    lines.put(158, "Most nincs ott dolgom.");
	    lines.put(159, "A bejárati ajtó.");
	    lines.put(160, "Nem az ajtó kulcsa.");
	    lines.put(161, "Nincs bezárva. Egyébként se idevaló a kulcs.");
	    lines.put(162, "Inkább magamnál tartom.");
	    lines.put(163, "Beépített szekrény.");
	    lines.put(164, "Nincs szükségem semmire belőle.");
	    lines.put(165, "Itt tudok kimenni.");
	    lines.put(166, "A wc fényeinek forrása.");
	    lines.put(167, "Nem kell kicserélni, még világít.");
	    lines.put(168, "Villanykapcsoló. Csodálatos találmány.");
	    lines.put(169, "Nincs kedvem sötétben gubbasztani a wc-n.");
	    lines.put(170, "Remek 20 literes, takarékos wc-tartály.");
	    lines.put(171, "Most komolyan, mit csináljak vele?");
	    lines.put(172, "El ne felejtsek majd újat rakni.");
	    lines.put(173, "Elég kevés papír van már. Hamarosan cserélni kell.");
	    lines.put(174, "Már kivettem a papírt.");
	    lines.put(175, "Nem szerelem le a falról.");
	    lines.put(176, "Alföldi wc csésze. Elég kényelmes.");
	    lines.put(177, "Hagyományos wckefe.");
	    lines.put(178, "Talán jól jön még.");
	    lines.put(179, "Nem fogom magammal cipelni.");
	    lines.put(180, "Most nem kell.");
	    lines.put(181, "Túl erős a lánc, hogy letépjem puszta kézzel.");
	    lines.put(182, "Nem húzom le feleslegesen. Vízpazarlás.");
	    lines.put(183, "Ez a lánc talán jó lenne Szurdinak.");
	    lines.put(184, "Hagyományos wc-lánc.");
	    lines.put(185, "Lássuk, ezzel le tudom-e vágni.");
	    lines.put(186, "Sikerült.");
	    lines.put(187, "Lassan újat kell rakni, mert elfogy.");
	    lines.put(188, "Ki tudja mire lesz még jó.");
//	    lines.put(1, "");
        lines.put(189, "Visszateszem, nehogy elfelejtsem.");
	    lines.put(190, "Nincs bezárva.");
	    lines.put(191, "Na persze. Nem fogok wc-t pucolni.");
	    lines.put(192, "A bejárat a házunkba.");
	    lines.put(193, "Ezzel lehet felcsöngetni a lakásokba.");
	    lines.put(194, "Van kulcsom, nem kell csengetni.");
	    lines.put(195, "A kisbolt megint zárva. Pedig elméletileg nonstop.");
	    lines.put(196, "Zárva van. Ha így megyek be az betörésnek minősül.");  
	    lines.put(197, "Hamarosan megjelenik a Kalyber Joe harmadik része.");  
	    lines.put(198, "Na majd Rolitól megveszem.");
	    lines.put(199, "Ha kell poszter, akkor Rolitól kérek.");
	    lines.put(200, "Nem a bejárati ajtó kulcsa.");
	    lines.put(201, "Nem ezt nyitja.");
	    lines.put(67, "Akkor most szólok.");
	    lines.put(202, "Fú! Most jut eszembe, hogy trolibérletet kéne venni.");
		lines.put(203, "Dehát annyi pénzem nincs is. Most mi lesz.");
		lines.put(204, "Egy hagyományos kuka.");
		lines.put(205, "Jól van, jól van.");
		lines.put(206, "A maga kukája? Nem látom rajta a nevét.");
		lines.put(207, "Annyira nem érdekel.");
		lines.put(208, "Mindegy, amúgy se akartam igazából kukázni.");
		lines.put(209, "A csöves kalapja. Van benne egy kis lóvé.");
	    lines.put(210, "Inkább nem kockáztatom meg a verést.");
	    lines.put(211, "Persze, stimmt.");
	    lines.put(212, "Bocsánat, én hibám.");
	    lines.put(213, "Hopsz egy gyors mozdulat...");
	    lines.put(214, "Semmit, már itt se vagyok.");
	    lines.put(215, "Egy 500-ast sikerült kivennem.");
	    lines.put(216, "Itt se vagyok!");
	    lines.put(217, "Valahogy el kell terelnem a figyelmét, hogy szerezzek egy kis pénzt.");
	    lines.put(218, "Valahogy el kell terelnem a figyelmét, hogy szerezzek egy kis pénzt.");
	    lines.put(219, "Csak meg akartam nézni milyen anyagból van.");
	    lines.put(220, "Sikerült.");  
	    lines.put(221, "Én semmit!");
	    lines.put(222, "Isten ments.");
	    lines.put(223, "Na sikerült 200 Ft-ot szerezni.");
	    lines.put(224, "Mindenféle újság.");
	    lines.put(225, "Rengeteg újság. Itt mindent megtalálsz.");
	    lines.put(226, "Napilapok.");
	    lines.put(227, "A nénitõl kell kérni.");
	    lines.put(228, "Az újságosnénitõl kell kérni.");
	    lines.put(229, "A nénitõl kell kérni.");
	    lines.put(230, "Most én is híján vagyok a pénznek.");
	    lines.put(231, "Inkább a tagnak kéne adni.");
	    lines.put(232, "Nem dobom ki.");
	    lines.put(233, "Csak nem megyek már gyalog a városba.");
	    lines.put(234, "Nézzük, mikor jön a troli.");  
	    lines.put(235, "Szerencsére ilyenkor elég sűrűn jár.");
	    lines.put(236, "Mit kezdjek vele?");
	    lines.put(237, "Nemrég üríthették, mert üres.");
	    lines.put(238, "Üres. De amúgy se kukáznék.");
	    lines.put(239, "Valaki jól elintézte szegény padot.");
	    lines.put(240, "Ezt már nem nagyon lehet rendbehozni.");
	    lines.put(241, "Egy labda a tetőn. Egy kisgyerek biztos sír utána valahol.");  
	    lines.put(242, "Nem mászok fel érte.");  
	    lines.put(243, "Nem dobom ki.");
	    lines.put(244, "Megjött a troli.");
	    lines.put(245, "A troli nyitott ajtaja hívogatóan vár.");
	    lines.put(247, "Tiszta udvar, rendes ház.");
	    lines.put(248, "Na persze.");
	    lines.put(249, "Mit kezdjek vele?");
	    lines.put(250, "Valaki betörte az üveget és kilopta a plakátot.");
	    lines.put(251, "Nem nyúlok be. Még az üveg elvágná a kezem.");
	    lines.put(252, "Valami mozgást látok ott lenn.");
	    lines.put(253, "Nem hiszem, hogy fel bírnám emelni.");
	    lines.put(254, "Meg egyébként sincs dolgom a csatornában.");
	    lines.put(255, "Tele van ragasztva mindenféle koncertplakáttal.");
	    lines.put(256, "Ma este Smafu, Keserű giliszta és Csigavér lesz.");
	    lines.put(257, "Nem tépkedem le őket");
	    lines.put(258, "Nincs ott senki.");
	    lines.put(259, "Hahó, van ott valaki?");
	    lines.put(260, "Nemtom, mintha valaki lenne ott lenn.");
	    lines.put(261, "Mindegy, hagyjuk.");
	    lines.put(262, "");
	    lines.put(263, "");
		lines.put(264, "Szevasz Zsolti!");
	    lines.put(265, "Mit csinálsz itt?");
	    lines.put(266, "És, sikerült?");
	    lines.put(267, "Az gáz, akkor most nem megyek a budi közelébe.");
	    lines.put(268, "Egyébként az én erõsítõm is elromlott.");
	    lines.put(269, "Szerintem csak biztosítékot kell benne cserélni. Tudsz adni?");
	    lines.put(270, "Persze, azaz akartam hozni...");
	    lines.put(271, "Figyi még ma behozom");
	    lines.put(272, "Tudsz adni biztosítékot?");
	    lines.put(273, "Okés, igyekszem.");
	    lines.put(286, "Zsolti letette a lemezvágót.");
	    lines.put(287, "Na végre megvan a pénz a tagságira. Megyek gyors befizetni.");
        lines.put(288, "Ebben tartom a spórolt pénzem.");
        lines.put(289, "Szerencsére nem kell összetörni, mert kulccsal nyílik.");
        lines.put(290, "Csak tudnám hol van.");
        lines.put(291, "Ebben volt a pénzem.");
        lines.put(292, "Tárulj szezám! Lássuk mennyit spóroltam oly sok év alatt.");
        lines.put(293, "Hát ez csak 1900 Forint.");
        lines.put(294, "Kéne még egy százas, hogy be tudjam fizetni a tagit.");
        lines.put(295, "Már nyitva van.");
        lines.put(296, "Fordítva működik.");
        lines.put(297, "Lássuk...");
        lines.put(298, "Tessék."); 
        lines.put(300, "Köszönöm!");
        lines.put(301, "Hát annyim sajnos nincs."); 
        lines.put(302, "Persze, persze, azért köszönöm.");
        lines.put(303, "Jól van, na, próbálkozni lehet.");
        lines.put(304, "Azt hiszem jobb lesz nem elpazarolni a tagságipénzt.");
        lines.put(305, "Azt hiszem mégse kérem akkor.");
        lines.put(306, "Sajnos annyi pénz nincs nálam.");
        lines.put(307, "Tessék.");
        lines.put(309, "Annyi nincs nálam."); 
        lines.put(310, "És olcsóbb nincs?");
        lines.put(311, "Hm, kösz az infót.");
        lines.put(312, "Ja, éppen van nálam.");
        lines.put(313, "Persze, tessék.");
        lines.put(314, "Hm, kösz az infót.");
        lines.put(315, "Ok, meglátom, mit tehetek.");
        lines.put(316, "Egy hajléktalan koldul az újságos tövében.");  
        lines.put(317, "Úgy döntöttem, békén hagyom.");
        lines.put(318, "Jól van, nincs harag.");
        lines.put(319, "Bocsánat.");
        lines.put(320, "Nem bántom, majd a rendõrök elzavarják.");  
        lines.put(321, "Mit szólna egy kis italhoz?");  
        lines.put(322, "Egészségére.");
        lines.put(323, "Nem adok neki több pénzt, így is kifosztott.");
        lines.put(324, "Ez nem elég a tagságira.");
        lines.put(325, "Hiányzik még %d Forint.");
        lines.put(1325, "Ok, mindegy.");
        lines.put(326, "Zsolti, hoztam a tagságit!");
        lines.put(327, "Akkor most már ránézel az erõsítőmre?");
        lines.put(328, "Dehát nem is csinálod.");
        lines.put(329, "Na ne már, miért nem keresed meg?");
        lines.put(330, "Itt áll egy kinn, kérdezd meg tőle.");
        lines.put(331, "Okés, végülis miért ne. De aztán megnézed az erõsítõmet.");
        lines.put(332, "Egy kis olvasnivaló?");  
        lines.put(333, "Nincs mit. Jó olvasást.");
        lines.put(334, "Most szereztem vissza, nem adom megint oda neki.");
        lines.put(335, "Nem adok többet, mert elfogy.");
        lines.put(336, "Még egy cigit?");
        lines.put(337, "Egy cigit?");
        lines.put(338, "Szereztem neked cigit.");
        lines.put(339, "Akkor tudsz segíteni?");
        lines.put(340, "Hm, kösz az infót.");
        lines.put(341, "Egy cigit?");  
        lines.put(342, "Ok.");
        lines.put(343, "Egy cigit?");  
        lines.put(344, "Jó, csak nehogy elfogyjon.");
        lines.put(345, "Nem adok többet, mert elfogy.");
        lines.put(346, "Egy cigit?");  
        lines.put(347, "Az sajnos nincs.");
        lines.put(348, "Egy szendvicset?");
        lines.put(349, "Odaadom, ha visszaadja az újságomat.");
        lines.put(350, "Jobb, ha nem ajándékozom el.");  
        lines.put(351, "Hátha jó lesz még valamire.");
        lines.put(352, "Zsolti, egy kis olvasnivaló?");
        lines.put(353, "Teljes két oldalt szenteltek benne a Rock klubnak.");
        lines.put(354, "Hát nem.");
        lines.put(355, "Ok.");
        lines.put(356, "Ezt nézd Zsolti mit hoztam!");
        lines.put(357, "Fogjuk rá.");
        lines.put(358, "Nesze.");
        lines.put(359, "Na most már nézz rá az erõsítõmre.");
        lines.put(360, "Okés.");
        lines.put(361, "Jobb, ha most már békén hagyom.");
        lines.put(362, "De.");
        lines.put(363, "Ok, ok, bocs.");
        lines.put(364, "De...");
        lines.put(365, "Akkor ránézel az erõsítõmre?");
        lines.put(366, "Ok.");
        lines.put(367, "Akkor mi lesz?");
        lines.put(368, "Megvan már a lehúzó?");
        lines.put(369, "Nincs.");
        lines.put(370, "Akkor megnézed az erõsítõmet?");
        lines.put(371, "De nem azért adtam az újságot!");    
        lines.put(372, "Igen, de nincs nála.");
        lines.put(373, "Menj a fenébe! Én keressem a lehúzódat?");
        lines.put(374, "Francba.");
        lines.put(375, "Megvan már a lehúzó?");
        lines.put(376, "Nincs.");
        lines.put(377, "Akkor megnézed az erõsítõmet?");
        lines.put(378, "És mikor kezdessz neki?");    
        lines.put(379, "Nincs nála.");
        lines.put(380, "Menj a fenébe! Én keressem a lehúzódat?");
        lines.put(381, "Francba.");
        lines.put(382, "Zsolti egy cigit?");
        lines.put(383, "Ha ránézel az erõsítõmre, akkor adok.");
        lines.put(384, "Akkor adj már egy újat.");
        lines.put(385, "Köszi, most már nem zavarlak.");
        lines.put(386, "Nesze, tied lehet az egész.");
        lines.put(387, "Egy cigit, Zsolti?");
        lines.put(388, "Aztán nehogy elfogyjon.");
        lines.put(389, "A malacperselyem kulcsa.");  
        lines.put(390, "El ne felejtsem majd hazavinni.");  
        lines.put(391, "Remélem nem megy most senki otthon wc-re.");  
        lines.put(392, "Tiszta rablás egy jegyért ennyi pénzt elkérni.");  
        lines.put(393, "Ezt már nem lehet mire használni.");  
        lines.put(394, "Teljesen érintetlten szendvics.");  
        lines.put(395, "Nem tudom, miért dobta ki a gazdája.");
        lines.put(396, "Mai Délmagyar különkiadás.");  
        lines.put(397, "Van benne egy cikk a Rock klubról.");
        lines.put(398, "Félig elfogyasztott márkátlan sör.");
        lines.put(399, "Valami külföldi cigi.");
        lines.put(400, "Jó erõs lemezvágó olló.");  
        lines.put(401, "A várva várt új biztosíték az erõsítõmbe.");  
        lines.put(402, "Ugyanaz az újságosnéni van már itt mióta az eszemet tudom.");
        lines.put(403, "El ne felejtsek újat rakni, ha hazaérek.");  
        lines.put(404, "Nem adom oda a pénzem, elõbb kérni kell valamit.");  
        lines.put(405, "Nem menne vele semmire");  
        lines.put(406, "Nem adom oda. Tele van pénzzel, ami nekem kell a tagságira.");
        lines.put(407, "Nem.");
        lines.put(408, "Nem.");
        lines.put(409, "Nem.");
        lines.put(410, "Nem.");
        lines.put(411, "Kétlem, hogy visszavenné az újságot.");  
        lines.put(412, "Elõbb ki kéne belõle venni a pénzt.");
        lines.put(413, "Használt jegyet nem vesznek vissza.");  
        lines.put(414, "Egy kortyot?");  
        lines.put(415, "Én csak kínáltam. Én nem iszok alkoholt.");
        lines.put(416, "Egy slukkot?");  
        lines.put(417, "Már nagykorú vagyok, de amúgy se cigizek.");
        lines.put(418, "Nem éhes? Van egy szendóm.");  
        lines.put(419, "Á, dehogy.");
        lines.put(420, "A Rock-klub atyaúristene.");  
        lines.put(421, "Nem lenne jó ötlet piszkálni.");    
        lines.put(422, "Egy keménykötésű punk.");
        lines.put(423, "Nem lenne jó kikezdeni vele.");  
        lines.put(424, "Erõsebbnek néz ki nálam.");
        lines.put(425, "Nem akarom csak úgy odaadni akárkinek.");  
        lines.put(426, "Egy kis olvasnivaló?"); 
        lines.put(427, "Tán nem tudsz olvasni?");
        lines.put(428, "Már itt se vagyok.");
        lines.put(429, "Nem akarom odaadni akárkinek.");  
        lines.put(430, "Jobb lesz nem felidegesíteni.");
        lines.put(431, "Hoztam egy wc-kefét.");  
        lines.put(432, "Ja, bocs.");
        lines.put(433, "Nem adom oda neki, hátha még kell valamire.");  
        lines.put(434, "Nem kell egy buszjegy?");  
        lines.put(435, "Akkor vegyen magának.");
        lines.put(436, "Nem kell egy buszjegy?");  
        lines.put(437, "Távol álljon tõlem.");
        lines.put(438, "Nem fogom nekiadni a nehezen összegyűjtött pénzemet.");  
        lines.put(439, "Zsolti, egy falást?");
        lines.put(440, "Nem mutatom meg neki, mert még visszakéri.");
        lines.put(441, "Segítessz beszerelni?");
        lines.put(442, "Jól van.");
        lines.put(443, "Nem adakozok.");  
        lines.put(444, "Nem kell egy jegy?");  
        lines.put(445, "Tényleg, nem is láttam.");
        lines.put(446, "Nem kell egy fogkefe?");  
        lines.put(447, "Nézd, szereztem egy láncot."); 
 	}
}